// Mocks generated by Mockito 5.4.4 from annotations
// in permacalendar/test/features/plant_intelligence/domain/services/plant_intelligence_orchestrator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:permacalendar/core/models/unified_garden_context.dart' as _i2;
import 'package:permacalendar/core/services/aggregation/garden_aggregation_hub.dart'
    as _i18;
import 'package:permacalendar/features/plant_catalog/data/models/plant_hive.dart'
    as _i20;
import 'package:permacalendar/features/plant_catalog/data/repositories/plant_hive_repository.dart'
    as _i19;
import 'package:permacalendar/features/plant_catalog/domain/entities/plant_entity.dart'
    as _i12;
import 'package:permacalendar/features/plant_intelligence/domain/entities/garden_context.dart'
    as _i11;
import 'package:permacalendar/features/plant_intelligence/domain/entities/intelligence_report.dart'
    as _i16;
import 'package:permacalendar/features/plant_intelligence/domain/entities/plant_condition.dart'
    as _i6;
import 'package:permacalendar/features/plant_intelligence/domain/entities/plant_evolution_report.dart'
    as _i17;
import 'package:permacalendar/features/plant_intelligence/domain/entities/recommendation.dart'
    as _i14;
import 'package:permacalendar/features/plant_intelligence/domain/entities/weather_condition.dart'
    as _i9;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_analytics_repository.dart'
    as _i15;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_garden_context_repository.dart'
    as _i10;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_plant_condition_repository.dart'
    as _i4;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_recommendation_repository.dart'
    as _i13;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_weather_repository.dart'
    as _i8;
import 'package:permacalendar/features/plant_intelligence/domain/services/plant_intelligence_evolution_tracker.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnifiedGardenContext_0 extends _i1.SmartFake
    implements _i2.UnifiedGardenContext {
  _FakeUnifiedGardenContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnifiedGardenStats_1 extends _i1.SmartFake
    implements _i2.UnifiedGardenStats {
  _FakeUnifiedGardenStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIntelligenceEvolutionSummary_2 extends _i1.SmartFake
    implements _i3.IntelligenceEvolutionSummary {
  _FakeIntelligenceEvolutionSummary_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPlantConditionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlantConditionRepository extends _i1.Mock
    implements _i4.IPlantConditionRepository {
  MockIPlantConditionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> savePlantCondition({
    required String? plantId,
    required _i6.PlantCondition? condition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlantCondition,
          [],
          {
            #plantId: plantId,
            #condition: condition,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #savePlantCondition,
            [],
            {
              #plantId: plantId,
              #condition: condition,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i6.PlantCondition?> getCurrentPlantCondition(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPlantCondition,
          [plantId],
        ),
        returnValue: _i5.Future<_i6.PlantCondition?>.value(),
      ) as _i5.Future<_i6.PlantCondition?>);

  @override
  _i5.Future<List<_i6.PlantCondition>> getPlantConditionHistory({
    required String? plantId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantConditionHistory,
          [],
          {
            #plantId: plantId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<List<_i6.PlantCondition>>.value(<_i6.PlantCondition>[]),
      ) as _i5.Future<List<_i6.PlantCondition>>);

  @override
  _i5.Future<bool> updatePlantCondition({
    required String? conditionId,
    required _i6.PlantCondition? condition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlantCondition,
          [],
          {
            #conditionId: conditionId,
            #condition: condition,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deletePlantCondition(String? conditionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlantCondition,
          [conditionId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [IWeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWeatherRepository extends _i1.Mock
    implements _i8.IWeatherRepository {
  MockIWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveWeatherCondition({
    required String? gardenId,
    required _i9.WeatherCondition? weather,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeatherCondition,
          [],
          {
            #gardenId: gardenId,
            #weather: weather,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveWeatherCondition,
            [],
            {
              #gardenId: gardenId,
              #weather: weather,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i9.WeatherCondition?> getCurrentWeatherCondition(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeatherCondition,
          [gardenId],
        ),
        returnValue: _i5.Future<_i9.WeatherCondition?>.value(),
      ) as _i5.Future<_i9.WeatherCondition?>);

  @override
  _i5.Future<List<_i9.WeatherCondition>> getWeatherHistory({
    required String? gardenId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherHistory,
          [],
          {
            #gardenId: gardenId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i9.WeatherCondition>>.value(
            <_i9.WeatherCondition>[]),
      ) as _i5.Future<List<_i9.WeatherCondition>>);
}

/// A class which mocks [IGardenContextRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIGardenContextRepository extends _i1.Mock
    implements _i10.IGardenContextRepository {
  MockIGardenContextRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveGardenContext(_i11.GardenContext? garden) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGardenContext,
          [garden],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveGardenContext,
            [garden],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i11.GardenContext?> getGardenContext(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenContext,
          [gardenId],
        ),
        returnValue: _i5.Future<_i11.GardenContext?>.value(),
      ) as _i5.Future<_i11.GardenContext?>);

  @override
  _i5.Future<bool> updateGardenContext(_i11.GardenContext? garden) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGardenContext,
          [garden],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i11.GardenContext>> getUserGardens(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGardens,
          [userId],
        ),
        returnValue:
            _i5.Future<List<_i11.GardenContext>>.value(<_i11.GardenContext>[]),
      ) as _i5.Future<List<_i11.GardenContext>>);

  @override
  _i5.Future<List<_i12.PlantFreezed>> getGardenPlants(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenPlants,
          [gardenId],
        ),
        returnValue:
            _i5.Future<List<_i12.PlantFreezed>>.value(<_i12.PlantFreezed>[]),
      ) as _i5.Future<List<_i12.PlantFreezed>>);

  @override
  _i5.Future<List<_i12.PlantFreezed>> searchPlants(
          Map<String, dynamic>? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [criteria],
        ),
        returnValue:
            _i5.Future<List<_i12.PlantFreezed>>.value(<_i12.PlantFreezed>[]),
      ) as _i5.Future<List<_i12.PlantFreezed>>);
}

/// A class which mocks [IRecommendationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRecommendationRepository extends _i1.Mock
    implements _i13.IRecommendationRepository {
  MockIRecommendationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveRecommendation({
    required String? plantId,
    required _i14.Recommendation? recommendation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecommendation,
          [],
          {
            #plantId: plantId,
            #recommendation: recommendation,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveRecommendation,
            [],
            {
              #plantId: plantId,
              #recommendation: recommendation,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i14.Recommendation>> getActiveRecommendations({
    required String? plantId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecommendations,
          [],
          {
            #plantId: plantId,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i14.Recommendation>>.value(
            <_i14.Recommendation>[]),
      ) as _i5.Future<List<_i14.Recommendation>>);

  @override
  _i5.Future<List<_i14.Recommendation>> getRecommendationsByPriority({
    required String? plantId,
    required String? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendationsByPriority,
          [],
          {
            #plantId: plantId,
            #priority: priority,
          },
        ),
        returnValue: _i5.Future<List<_i14.Recommendation>>.value(
            <_i14.Recommendation>[]),
      ) as _i5.Future<List<_i14.Recommendation>>);

  @override
  _i5.Future<bool> markRecommendationAsApplied({
    required String? recommendationId,
    DateTime? appliedAt,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecommendationAsApplied,
          [],
          {
            #recommendationId: recommendationId,
            #appliedAt: appliedAt,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> markRecommendationAsIgnored({
    required String? recommendationId,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecommendationAsIgnored,
          [],
          {
            #recommendationId: recommendationId,
            #reason: reason,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteRecommendation(String? recommendationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecommendation,
          [recommendationId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i14.Recommendation>> filterRecommendations(
          Map<String, dynamic>? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterRecommendations,
          [criteria],
        ),
        returnValue: _i5.Future<List<_i14.Recommendation>>.value(
            <_i14.Recommendation>[]),
      ) as _i5.Future<List<_i14.Recommendation>>);
}

/// A class which mocks [IAnalyticsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAnalyticsRepository extends _i1.Mock
    implements _i15.IAnalyticsRepository {
  MockIAnalyticsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> saveAnalysisResult({
    required String? plantId,
    required String? analysisType,
    required Map<String, dynamic>? result,
    required double? confidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalysisResult,
          [],
          {
            #plantId: plantId,
            #analysisType: analysisType,
            #result: result,
            #confidence: confidence,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveAnalysisResult,
            [],
            {
              #plantId: plantId,
              #analysisType: analysisType,
              #result: result,
              #confidence: confidence,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Map<String, dynamic>?> getLatestAnalysis({
    required String? plantId,
    required String? analysisType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestAnalysis,
          [],
          {
            #plantId: plantId,
            #analysisType: analysisType,
          },
        ),
        returnValue: _i5.Future<Map<String, dynamic>?>.value(),
      ) as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getAnalysisHistory({
    required String? plantId,
    String? analysisType,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnalysisHistory,
          [],
          {
            #plantId: plantId,
            #analysisType: analysisType,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> getPlantHealthStats({
    required String? plantId,
    int? period = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantHealthStats,
          [],
          {
            #plantId: plantId,
            #period: period,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> getGardenPerformanceMetrics({
    required String? gardenId,
    int? period = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenPerformanceMetrics,
          [],
          {
            #gardenId: gardenId,
            #period: period,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getTrendData({
    required String? plantId,
    required String? metric,
    int? period = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendData,
          [],
          {
            #plantId: plantId,
            #metric: metric,
            #period: period,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<String> saveAlert({
    required String? plantId,
    required String? alertType,
    required String? severity,
    required String? message,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAlert,
          [],
          {
            #plantId: plantId,
            #alertType: alertType,
            #severity: severity,
            #message: message,
            #data: data,
          },
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #saveAlert,
            [],
            {
              #plantId: plantId,
              #alertType: alertType,
              #severity: severity,
              #message: message,
              #data: data,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getActiveAlerts({
    String? plantId,
    String? gardenId,
    String? severity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAlerts,
          [],
          {
            #plantId: plantId,
            #gardenId: gardenId,
            #severity: severity,
          },
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<bool> resolveAlert({
    required String? alertId,
    DateTime? resolvedAt,
    String? resolution,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveAlert,
          [],
          {
            #alertId: alertId,
            #resolvedAt: resolvedAt,
            #resolution: resolution,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> saveLatestReport(_i16.PlantIntelligenceReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLatestReport,
          [report],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i16.PlantIntelligenceReport?> getLastReport(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastReport,
          [plantId],
        ),
        returnValue: _i5.Future<_i16.PlantIntelligenceReport?>.value(),
      ) as _i5.Future<_i16.PlantIntelligenceReport?>);

  @override
  _i5.Future<void> saveEvolutionReport(_i17.PlantEvolutionReport? report) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEvolutionReport,
          [report],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i17.PlantEvolutionReport>> getEvolutionReports(
          String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutionReports,
          [plantId],
        ),
        returnValue: _i5.Future<List<_i17.PlantEvolutionReport>>.value(
            <_i17.PlantEvolutionReport>[]),
      ) as _i5.Future<List<_i17.PlantEvolutionReport>>);
}

/// A class which mocks [GardenAggregationHub].
///
/// See the documentation for Mockito's code generation for more information.
class MockGardenAggregationHub extends _i1.Mock
    implements _i18.GardenAggregationHub {
  MockGardenAggregationHub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UnifiedGardenContext> getUnifiedContext(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnifiedContext,
          [gardenId],
        ),
        returnValue: _i5.Future<_i2.UnifiedGardenContext>.value(
            _FakeUnifiedGardenContext_0(
          this,
          Invocation.method(
            #getUnifiedContext,
            [gardenId],
          ),
        )),
      ) as _i5.Future<_i2.UnifiedGardenContext>);

  @override
  _i5.Future<List<_i2.UnifiedPlantData>> getActivePlants(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePlants,
          [gardenId],
        ),
        returnValue: _i5.Future<List<_i2.UnifiedPlantData>>.value(
            <_i2.UnifiedPlantData>[]),
      ) as _i5.Future<List<_i2.UnifiedPlantData>>);

  @override
  _i5.Future<List<_i2.UnifiedPlantData>> getHistoricalPlants(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoricalPlants,
          [gardenId],
        ),
        returnValue: _i5.Future<List<_i2.UnifiedPlantData>>.value(
            <_i2.UnifiedPlantData>[]),
      ) as _i5.Future<List<_i2.UnifiedPlantData>>);

  @override
  _i5.Future<_i2.UnifiedPlantData?> getPlantById(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantById,
          [plantId],
        ),
        returnValue: _i5.Future<_i2.UnifiedPlantData?>.value(),
      ) as _i5.Future<_i2.UnifiedPlantData?>);

  @override
  _i5.Future<_i2.UnifiedGardenStats> getGardenStats(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenStats,
          [gardenId],
        ),
        returnValue:
            _i5.Future<_i2.UnifiedGardenStats>.value(_FakeUnifiedGardenStats_1(
          this,
          Invocation.method(
            #getGardenStats,
            [gardenId],
          ),
        )),
      ) as _i5.Future<_i2.UnifiedGardenStats>);

  @override
  _i5.Future<List<_i2.UnifiedActivityHistory>> getRecentActivities(
    String? gardenId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentActivities,
          [gardenId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i2.UnifiedActivityHistory>>.value(
            <_i2.UnifiedActivityHistory>[]),
      ) as _i5.Future<List<_i2.UnifiedActivityHistory>>);

  @override
  void invalidateCache(String? gardenId) => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [gardenId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? getIntelligenceCache(String? gardenId) =>
      (super.noSuchMethod(Invocation.method(
        #getIntelligenceCache,
        [gardenId],
      )) as Map<String, dynamic>?);

  @override
  void setIntelligenceCache(
    String? gardenId,
    Map<String, dynamic>? data,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setIntelligenceCache,
          [
            gardenId,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateGardenIntelligenceCache(String? gardenId) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateGardenIntelligenceCache,
          [gardenId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllIntelligenceCaches() => super.noSuchMethod(
        Invocation.method(
          #clearAllIntelligenceCaches,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getIntelligenceCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getIntelligenceCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<Map<String, dynamic>> healthCheck() => (super.noSuchMethod(
        Invocation.method(
          #healthCheck,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);
}

/// A class which mocks [PlantHiveRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantHiveRepository extends _i1.Mock
    implements _i19.PlantHiveRepository {
  MockPlantHiveRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<List<_i12.PlantFreezed>> getAllPlants() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue:
            _i5.Future<List<_i12.PlantFreezed>>.value(<_i12.PlantFreezed>[]),
      ) as _i5.Future<List<_i12.PlantFreezed>>);

  @override
  _i5.Future<_i12.PlantFreezed?> getPlantById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantById,
          [id],
        ),
        returnValue: _i5.Future<_i12.PlantFreezed?>.value(),
      ) as _i5.Future<_i12.PlantFreezed?>);

  @override
  _i5.Future<void> initializeFromJson() => (super.noSuchMethod(
        Invocation.method(
          #initializeFromJson,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> addPlant(_i20.PlantHive? plant) => (super.noSuchMethod(
        Invocation.method(
          #addPlant,
          [plant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePlant(_i20.PlantHive? plant) => (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deletePlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [plantId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> plantExists(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #plantExists,
          [plantId],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [PlantIntelligenceEvolutionTracker].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantIntelligenceEvolutionTracker extends _i1.Mock
    implements _i3.PlantIntelligenceEvolutionTracker {
  MockPlantIntelligenceEvolutionTracker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get enableLogging => (super.noSuchMethod(
        Invocation.getter(#enableLogging),
        returnValue: false,
      ) as bool);

  @override
  double get toleranceThreshold => (super.noSuchMethod(
        Invocation.getter(#toleranceThreshold),
        returnValue: 0.0,
      ) as double);

  @override
  _i3.IntelligenceEvolutionSummary compareReports(
    _i16.PlantIntelligenceReport? oldReport,
    _i16.PlantIntelligenceReport? newReport,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #compareReports,
          [
            oldReport,
            newReport,
          ],
        ),
        returnValue: _FakeIntelligenceEvolutionSummary_2(
          this,
          Invocation.method(
            #compareReports,
            [
              oldReport,
              newReport,
            ],
          ),
        ),
      ) as _i3.IntelligenceEvolutionSummary);

  @override
  List<_i3.IntelligenceEvolutionSummary> compareGardenReports(
    List<_i16.PlantIntelligenceReport>? oldReports,
    List<_i16.PlantIntelligenceReport>? newReports,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #compareGardenReports,
          [
            oldReports,
            newReports,
          ],
        ),
        returnValue: <_i3.IntelligenceEvolutionSummary>[],
      ) as List<_i3.IntelligenceEvolutionSummary>);
}

