// Mocks generated by Mockito 5.4.4 from annotations
// in permacalendar/test/core/services/garden_event_observer_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permacalendar/features/plant_catalog/domain/entities/plant_entity.dart'
    as _i5;
import 'package:permacalendar/features/plant_intelligence/domain/entities/intelligence_report.dart'
    as _i2;
import 'package:permacalendar/features/plant_intelligence/domain/services/plant_intelligence_orchestrator.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlantIntelligenceReport_0 extends _i1.SmartFake
    implements _i2.PlantIntelligenceReport {
  _FakePlantIntelligenceReport_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlantIntelligenceOrchestrator].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantIntelligenceOrchestrator extends _i1.Mock
    implements _i3.PlantIntelligenceOrchestrator {
  MockPlantIntelligenceOrchestrator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.PlantIntelligenceReport> generateIntelligenceReport({
    required String? plantId,
    required String? gardenId,
    _i5.PlantFreezed? plant,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateIntelligenceReport,
          [],
          {
            #plantId: plantId,
            #gardenId: gardenId,
            #plant: plant,
          },
        ),
        returnValue: _i4.Future<_i2.PlantIntelligenceReport>.value(
            _FakePlantIntelligenceReport_0(
          this,
          Invocation.method(
            #generateIntelligenceReport,
            [],
            {
              #plantId: plantId,
              #gardenId: gardenId,
              #plant: plant,
            },
          ),
        )),
      ) as _i4.Future<_i2.PlantIntelligenceReport>);

  @override
  _i4.Future<List<_i2.PlantIntelligenceReport>>
      generateGardenIntelligenceReport({required String? gardenId}) =>
          (super.noSuchMethod(
            Invocation.method(
              #generateGardenIntelligenceReport,
              [],
              {#gardenId: gardenId},
            ),
            returnValue: _i4.Future<List<_i2.PlantIntelligenceReport>>.value(
                <_i2.PlantIntelligenceReport>[]),
          ) as _i4.Future<List<_i2.PlantIntelligenceReport>>);
}
