// Mocks generated by Mockito 5.4.4 from annotations
// in permacalendar/test/features/plant_intelligence/domain/usecases/analyze_pest_threats_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permacalendar/features/plant_catalog/domain/entities/plant_entity.dart'
    as _i8;
import 'package:permacalendar/features/plant_intelligence/domain/entities/pest.dart'
    as _i6;
import 'package:permacalendar/features/plant_intelligence/domain/entities/pest_observation.dart'
    as _i4;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_pest_observation_repository.dart'
    as _i2;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_pest_repository.dart'
    as _i5;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_plant_data_source.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IPestObservationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPestObservationRepository extends _i1.Mock
    implements _i2.IPestObservationRepository {
  MockIPestObservationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> savePestObservation(_i4.PestObservation? observation) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePestObservation,
          [observation],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePestObservation(_i4.PestObservation? observation) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePestObservation,
          [observation],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.PestObservation>> getObservationsForGarden(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObservationsForGarden,
          [gardenId],
        ),
        returnValue: _i3.Future<List<_i4.PestObservation>>.value(
            <_i4.PestObservation>[]),
      ) as _i3.Future<List<_i4.PestObservation>>);

  @override
  _i3.Future<List<_i4.PestObservation>> getActiveObservations(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveObservations,
          [gardenId],
        ),
        returnValue: _i3.Future<List<_i4.PestObservation>>.value(
            <_i4.PestObservation>[]),
      ) as _i3.Future<List<_i4.PestObservation>>);

  @override
  _i3.Future<List<_i4.PestObservation>> getObservationsForPlant(
          String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObservationsForPlant,
          [plantId],
        ),
        returnValue: _i3.Future<List<_i4.PestObservation>>.value(
            <_i4.PestObservation>[]),
      ) as _i3.Future<List<_i4.PestObservation>>);

  @override
  _i3.Future<_i4.PestObservation?> getObservation(String? observationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObservation,
          [observationId],
        ),
        returnValue: _i3.Future<_i4.PestObservation?>.value(),
      ) as _i3.Future<_i4.PestObservation?>);

  @override
  _i3.Future<void> resolveObservation(
    String? observationId,
    String? resolutionMethod,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveObservation,
          [
            observationId,
            resolutionMethod,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteObservation(String? observationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteObservation,
          [observationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [IPestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPestRepository extends _i1.Mock implements _i5.IPestRepository {
  MockIPestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.Pest?> getPest(String? pestId) => (super.noSuchMethod(
        Invocation.method(
          #getPest,
          [pestId],
        ),
        returnValue: _i3.Future<_i6.Pest?>.value(),
      ) as _i3.Future<_i6.Pest?>);

  @override
  _i3.Future<List<_i6.Pest>> getAllPests() => (super.noSuchMethod(
        Invocation.method(
          #getAllPests,
          [],
        ),
        returnValue: _i3.Future<List<_i6.Pest>>.value(<_i6.Pest>[]),
      ) as _i3.Future<List<_i6.Pest>>);

  @override
  _i3.Future<List<_i6.Pest>> getPestsForPlant(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPestsForPlant,
          [plantId],
        ),
        returnValue: _i3.Future<List<_i6.Pest>>.value(<_i6.Pest>[]),
      ) as _i3.Future<List<_i6.Pest>>);

  @override
  _i3.Future<List<_i6.Pest>> searchPests(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchPests,
          [query],
        ),
        returnValue: _i3.Future<List<_i6.Pest>>.value(<_i6.Pest>[]),
      ) as _i3.Future<List<_i6.Pest>>);

  @override
  _i3.Future<List<_i6.Pest>> getPestsBySeverity(_i6.PestSeverity? severity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPestsBySeverity,
          [severity],
        ),
        returnValue: _i3.Future<List<_i6.Pest>>.value(<_i6.Pest>[]),
      ) as _i3.Future<List<_i6.Pest>>);
}

/// A class which mocks [IPlantDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlantDataSource extends _i1.Mock implements _i7.IPlantDataSource {
  MockIPlantDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i8.PlantFreezed?> getPlant(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlant,
          [plantId],
        ),
        returnValue: _i3.Future<_i8.PlantFreezed?>.value(),
      ) as _i3.Future<_i8.PlantFreezed?>);

  @override
  _i3.Future<List<_i8.PlantFreezed>> getAllPlants() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue:
            _i3.Future<List<_i8.PlantFreezed>>.value(<_i8.PlantFreezed>[]),
      ) as _i3.Future<List<_i8.PlantFreezed>>);

  @override
  _i3.Future<List<_i8.PlantFreezed>> searchPlants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue:
            _i3.Future<List<_i8.PlantFreezed>>.value(<_i8.PlantFreezed>[]),
      ) as _i3.Future<List<_i8.PlantFreezed>>);
}
