// Mocks generated by Mockito 5.4.4 from annotations
// in permacalendar/test/features/plant_intelligence/domain/usecases/generate_bio_control_recommendations_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:permacalendar/features/plant_catalog/domain/entities/plant_entity.dart'
    as _i9;
import 'package:permacalendar/features/plant_intelligence/domain/entities/beneficial_insect.dart'
    as _i7;
import 'package:permacalendar/features/plant_intelligence/domain/entities/pest.dart'
    as _i5;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_beneficial_insect_repository.dart'
    as _i6;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_pest_repository.dart'
    as _i3;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_plant_data_source.dart'
    as _i8;
import 'package:uuid/data.dart' as _i11;
import 'package:uuid/uuid.dart' as _i10;
import 'package:uuid/uuid_value.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUuidValue_0 extends _i1.SmartFake implements _i2.UuidValue {
  _FakeUuidValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IPestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPestRepository extends _i1.Mock implements _i3.IPestRepository {
  MockIPestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.Pest?> getPest(String? pestId) => (super.noSuchMethod(
        Invocation.method(
          #getPest,
          [pestId],
        ),
        returnValue: _i4.Future<_i5.Pest?>.value(),
      ) as _i4.Future<_i5.Pest?>);

  @override
  _i4.Future<List<_i5.Pest>> getAllPests() => (super.noSuchMethod(
        Invocation.method(
          #getAllPests,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Pest>>.value(<_i5.Pest>[]),
      ) as _i4.Future<List<_i5.Pest>>);

  @override
  _i4.Future<List<_i5.Pest>> getPestsForPlant(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPestsForPlant,
          [plantId],
        ),
        returnValue: _i4.Future<List<_i5.Pest>>.value(<_i5.Pest>[]),
      ) as _i4.Future<List<_i5.Pest>>);

  @override
  _i4.Future<List<_i5.Pest>> searchPests(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchPests,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.Pest>>.value(<_i5.Pest>[]),
      ) as _i4.Future<List<_i5.Pest>>);

  @override
  _i4.Future<List<_i5.Pest>> getPestsBySeverity(_i5.PestSeverity? severity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPestsBySeverity,
          [severity],
        ),
        returnValue: _i4.Future<List<_i5.Pest>>.value(<_i5.Pest>[]),
      ) as _i4.Future<List<_i5.Pest>>);
}

/// A class which mocks [IBeneficialInsectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBeneficialInsectRepository extends _i1.Mock
    implements _i6.IBeneficialInsectRepository {
  MockIBeneficialInsectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i7.BeneficialInsect?> getInsect(String? insectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsect,
          [insectId],
        ),
        returnValue: _i4.Future<_i7.BeneficialInsect?>.value(),
      ) as _i4.Future<_i7.BeneficialInsect?>);

  @override
  _i4.Future<List<_i7.BeneficialInsect>> getAllInsects() => (super.noSuchMethod(
        Invocation.method(
          #getAllInsects,
          [],
        ),
        returnValue: _i4.Future<List<_i7.BeneficialInsect>>.value(
            <_i7.BeneficialInsect>[]),
      ) as _i4.Future<List<_i7.BeneficialInsect>>);

  @override
  _i4.Future<List<_i7.BeneficialInsect>> getPredatorsOf(String? pestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPredatorsOf,
          [pestId],
        ),
        returnValue: _i4.Future<List<_i7.BeneficialInsect>>.value(
            <_i7.BeneficialInsect>[]),
      ) as _i4.Future<List<_i7.BeneficialInsect>>);

  @override
  _i4.Future<List<_i7.BeneficialInsect>> getInsectsAttractedTo(
          String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsectsAttractedTo,
          [plantId],
        ),
        returnValue: _i4.Future<List<_i7.BeneficialInsect>>.value(
            <_i7.BeneficialInsect>[]),
      ) as _i4.Future<List<_i7.BeneficialInsect>>);

  @override
  _i4.Future<List<_i7.BeneficialInsect>> searchInsects(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInsects,
          [query],
        ),
        returnValue: _i4.Future<List<_i7.BeneficialInsect>>.value(
            <_i7.BeneficialInsect>[]),
      ) as _i4.Future<List<_i7.BeneficialInsect>>);
}

/// A class which mocks [IPlantDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlantDataSource extends _i1.Mock implements _i8.IPlantDataSource {
  MockIPlantDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.PlantFreezed?> getPlant(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlant,
          [plantId],
        ),
        returnValue: _i4.Future<_i9.PlantFreezed?>.value(),
      ) as _i4.Future<_i9.PlantFreezed?>);

  @override
  _i4.Future<List<_i9.PlantFreezed>> getAllPlants() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue:
            _i4.Future<List<_i9.PlantFreezed>>.value(<_i9.PlantFreezed>[]),
      ) as _i4.Future<List<_i9.PlantFreezed>>);

  @override
  _i4.Future<List<_i9.PlantFreezed>> searchPlants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i9.PlantFreezed>>.value(<_i9.PlantFreezed>[]),
      ) as _i4.Future<List<_i9.PlantFreezed>>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i10.Uuid {
  MockUuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String v1({
    Map<String, dynamic>? options,
    _i11.V1Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v1,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as String);

  @override
  List<int> v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i11.V1Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1buffer,
          [buffer],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v1obj({
    Map<String, dynamic>? options,
    _i11.V1Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1obj,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v1obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v4({
    Map<String, dynamic>? options,
    _i11.V4Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v4,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as String);

  @override
  List<int> v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i11.V4Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4buffer,
          [buffer],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v4obj({
    Map<String, dynamic>? options,
    _i11.V4Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4obj,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v4obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i11.V5Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5,
          [
            namespace,
            name,
          ],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v5,
            [
              namespace,
              name,
            ],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as String);

  @override
  List<int> v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i11.V5Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5buffer,
          [
            namespace,
            name,
            buffer,
          ],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v5obj(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i11.V5Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5obj,
          [
            namespace,
            name,
          ],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v5obj,
            [
              namespace,
              name,
            ],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v6({_i11.V6Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v6,
          [],
          {#config: config},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v6,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v6buffer(
    List<int>? buffer, {
    _i11.V6Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v6buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v6obj({_i11.V6Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v6obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v6obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v7({_i11.V7Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v7,
          [],
          {#config: config},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v7,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v7buffer(
    List<int>? buffer, {
    _i11.V7Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v7buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v7obj({_i11.V7Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v7obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v7obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v8({_i11.V8Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8,
          [],
          {#config: config},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v8,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v8buffer(
    List<int>? buffer, {
    _i11.V8Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v8buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v8obj({_i11.V8Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v8obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);

  @override
  String v8g({_i11.V8GenericOptions? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8g,
          [],
          {#config: config},
        ),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.method(
            #v8g,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v8gbuffer(
    List<int>? buffer, {
    _i11.V8GenericOptions? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v8gbuffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i2.UuidValue v8gobj({_i11.V8GenericOptions? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8gobj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_0(
          this,
          Invocation.method(
            #v8gobj,
            [],
            {#config: config},
          ),
        ),
      ) as _i2.UuidValue);
}

