// Mocks generated by Mockito 5.4.4 from annotations
// in permacalendar/test/features/plant_intelligence/data/repositories/analytics_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permacalendar/core/models/unified_garden_context.dart' as _i2;
import 'package:permacalendar/core/services/aggregation/garden_aggregation_hub.dart'
    as _i10;
import 'package:permacalendar/features/plant_intelligence/data/datasources/plant_intelligence_local_datasource.dart'
    as _i3;
import 'package:permacalendar/features/plant_intelligence/domain/entities/garden_context.dart'
    as _i7;
import 'package:permacalendar/features/plant_intelligence/domain/entities/plant_condition.dart'
    as _i5;
import 'package:permacalendar/features/plant_intelligence/domain/entities/recommendation.dart'
    as _i8;
import 'package:permacalendar/features/plant_intelligence/domain/entities/weather_condition.dart'
    as _i6;
import 'package:permacalendar/features/plant_intelligence/domain/models/plant_freezed.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUnifiedGardenContext_0 extends _i1.SmartFake
    implements _i2.UnifiedGardenContext {
  _FakeUnifiedGardenContext_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnifiedGardenStats_1 extends _i1.SmartFake
    implements _i2.UnifiedGardenStats {
  _FakeUnifiedGardenStats_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlantIntelligenceLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantIntelligenceLocalDataSource extends _i1.Mock
    implements _i3.PlantIntelligenceLocalDataSource {
  MockPlantIntelligenceLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> savePlantCondition(_i5.PlantCondition? condition) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePlantCondition,
          [condition],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.PlantCondition?> getCurrentPlantCondition(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentPlantCondition,
          [plantId],
        ),
        returnValue: _i4.Future<_i5.PlantCondition?>.value(),
      ) as _i4.Future<_i5.PlantCondition?>);

  @override
  _i4.Future<List<_i5.PlantCondition>> getPlantConditionHistory({
    required String? plantId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantConditionHistory,
          [],
          {
            #plantId: plantId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.PlantCondition>>.value(<_i5.PlantCondition>[]),
      ) as _i4.Future<List<_i5.PlantCondition>>);

  @override
  _i4.Future<bool> updatePlantCondition(
    String? conditionId,
    _i5.PlantCondition? condition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlantCondition,
          [
            conditionId,
            condition,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deletePlantCondition(String? conditionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePlantCondition,
          [conditionId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveWeatherCondition(
    String? gardenId,
    _i6.WeatherCondition? weather,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeatherCondition,
          [
            gardenId,
            weather,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.WeatherCondition?> getCurrentWeatherCondition(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeatherCondition,
          [gardenId],
        ),
        returnValue: _i4.Future<_i6.WeatherCondition?>.value(),
      ) as _i4.Future<_i6.WeatherCondition?>);

  @override
  _i4.Future<List<_i6.WeatherCondition>> getWeatherHistory({
    required String? gardenId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherHistory,
          [],
          {
            #gardenId: gardenId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<_i6.WeatherCondition>>.value(
            <_i6.WeatherCondition>[]),
      ) as _i4.Future<List<_i6.WeatherCondition>>);

  @override
  _i4.Future<void> saveGardenContext(_i7.GardenContext? garden) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGardenContext,
          [garden],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i7.GardenContext?> getGardenContext(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenContext,
          [gardenId],
        ),
        returnValue: _i4.Future<_i7.GardenContext?>.value(),
      ) as _i4.Future<_i7.GardenContext?>);

  @override
  _i4.Future<bool> updateGardenContext(_i7.GardenContext? garden) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGardenContext,
          [garden],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i7.GardenContext>> getUserGardens(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserGardens,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i7.GardenContext>>.value(<_i7.GardenContext>[]),
      ) as _i4.Future<List<_i7.GardenContext>>);

  @override
  _i4.Future<void> saveRecommendation(
    String? plantId,
    _i8.Recommendation? recommendation,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecommendation,
          [
            plantId,
            recommendation,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.Recommendation>> getActiveRecommendations({
    required String? plantId,
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveRecommendations,
          [],
          {
            #plantId: plantId,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i8.Recommendation>>.value(<_i8.Recommendation>[]),
      ) as _i4.Future<List<_i8.Recommendation>>);

  @override
  _i4.Future<List<_i8.Recommendation>> getRecommendationsByPriority({
    required String? plantId,
    required String? priority,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendationsByPriority,
          [],
          {
            #plantId: plantId,
            #priority: priority,
          },
        ),
        returnValue:
            _i4.Future<List<_i8.Recommendation>>.value(<_i8.Recommendation>[]),
      ) as _i4.Future<List<_i8.Recommendation>>);

  @override
  _i4.Future<bool> markRecommendationAsApplied({
    required String? recommendationId,
    DateTime? appliedAt,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecommendationAsApplied,
          [],
          {
            #recommendationId: recommendationId,
            #appliedAt: appliedAt,
            #notes: notes,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> markRecommendationAsIgnored({
    required String? recommendationId,
    String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecommendationAsIgnored,
          [],
          {
            #recommendationId: recommendationId,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteRecommendation(String? recommendationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecommendation,
          [recommendationId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveAnalysisResult({
    required String? plantId,
    required String? analysisType,
    required Map<String, dynamic>? result,
    required double? confidence,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAnalysisResult,
          [],
          {
            #plantId: plantId,
            #analysisType: analysisType,
            #result: result,
            #confidence: confidence,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getLatestAnalysis({
    required String? plantId,
    required String? analysisType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestAnalysis,
          [],
          {
            #plantId: plantId,
            #analysisType: analysisType,
          },
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAnalysisHistory({
    required String? plantId,
    String? analysisType,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnalysisHistory,
          [],
          {
            #plantId: plantId,
            #analysisType: analysisType,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> saveAlert({
    required String? plantId,
    required String? alertType,
    required String? severity,
    required String? message,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveAlert,
          [],
          {
            #plantId: plantId,
            #alertType: alertType,
            #severity: severity,
            #message: message,
            #data: data,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getActiveAlerts({
    String? plantId,
    String? gardenId,
    String? severity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveAlerts,
          [],
          {
            #plantId: plantId,
            #gardenId: gardenId,
            #severity: severity,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> resolveAlert({
    required String? alertId,
    DateTime? resolvedAt,
    String? resolution,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveAlert,
          [],
          {
            #alertId: alertId,
            #resolvedAt: resolvedAt,
            #resolution: resolution,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> saveUserPreferences({
    required String? userId,
    required Map<String, dynamic>? preferences,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUserPreferences,
          [],
          {
            #userId: userId,
            #preferences: preferences,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserPreferences(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserPreferences,
          [userId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<bool> updateUserPreference({
    required String? userId,
    required String? key,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPreference,
          [],
          {
            #userId: userId,
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> getPlantHealthStats({
    required String? plantId,
    int? period = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantHealthStats,
          [],
          {
            #plantId: plantId,
            #period: period,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> getGardenPerformanceMetrics({
    required String? gardenId,
    int? period = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenPerformanceMetrics,
          [],
          {
            #gardenId: gardenId,
            #period: period,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getTrendData({
    required String? plantId,
    required String? metric,
    int? period = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrendData,
          [],
          {
            #plantId: plantId,
            #metric: metric,
            #period: period,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<bool> syncData({bool? forceSync = false}) => (super.noSuchMethod(
        Invocation.method(
          #syncData,
          [],
          {#forceSync: forceSync},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearCache({Duration? olderThan}) => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
          {#olderThan: olderThan},
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isHealthy() => (super.noSuchMethod(
        Invocation.method(
          #isHealthy,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i9.PlantFreezed>> searchPlants(
          Map<String, dynamic>? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [criteria],
        ),
        returnValue:
            _i4.Future<List<_i9.PlantFreezed>>.value(<_i9.PlantFreezed>[]),
      ) as _i4.Future<List<_i9.PlantFreezed>>);

  @override
  _i4.Future<List<_i8.Recommendation>> filterRecommendations(
          Map<String, dynamic>? criteria) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterRecommendations,
          [criteria],
        ),
        returnValue:
            _i4.Future<List<_i8.Recommendation>>.value(<_i8.Recommendation>[]),
      ) as _i4.Future<List<_i8.Recommendation>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> searchHistory({
    required String? query,
    required String? type,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchHistory,
          [],
          {
            #query: query,
            #type: type,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>> exportPlantData({
    required String? plantId,
    String? format = r'json',
    bool? includeHistory = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportPlantData,
          [],
          {
            #plantId: plantId,
            #format: format,
            #includeHistory: includeHistory,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> importPlantData({
    required Map<String, dynamic>? data,
    String? format = r'json',
    bool? overwrite = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importPlantData,
          [],
          {
            #data: data,
            #format: format,
            #overwrite: overwrite,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>> backupGarden({
    required String? gardenId,
    bool? includeHistory = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #backupGarden,
          [],
          {
            #gardenId: gardenId,
            #includeHistory: includeHistory,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> restoreGarden({
    required Map<String, dynamic>? backupData,
    required String? gardenId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreGarden,
          [],
          {
            #backupData: backupData,
            #gardenId: gardenId,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> saveIntelligenceReport(
    String? plantId,
    Map<String, dynamic>? reportJson,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveIntelligenceReport,
          [
            plantId,
            reportJson,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getIntelligenceReport(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIntelligenceReport,
          [plantId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> saveEvolutionReport(
          Map<String, dynamic>? evolutionReportJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveEvolutionReport,
          [evolutionReportJson],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getEvolutionReports(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvolutionReports,
          [plantId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GardenAggregationHub].
///
/// See the documentation for Mockito's code generation for more information.
class MockGardenAggregationHub extends _i1.Mock
    implements _i10.GardenAggregationHub {
  MockGardenAggregationHub() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UnifiedGardenContext> getUnifiedContext(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUnifiedContext,
          [gardenId],
        ),
        returnValue: _i4.Future<_i2.UnifiedGardenContext>.value(
            _FakeUnifiedGardenContext_0(
          this,
          Invocation.method(
            #getUnifiedContext,
            [gardenId],
          ),
        )),
      ) as _i4.Future<_i2.UnifiedGardenContext>);

  @override
  _i4.Future<List<_i2.UnifiedPlantData>> getActivePlants(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActivePlants,
          [gardenId],
        ),
        returnValue: _i4.Future<List<_i2.UnifiedPlantData>>.value(
            <_i2.UnifiedPlantData>[]),
      ) as _i4.Future<List<_i2.UnifiedPlantData>>);

  @override
  _i4.Future<List<_i2.UnifiedPlantData>> getHistoricalPlants(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHistoricalPlants,
          [gardenId],
        ),
        returnValue: _i4.Future<List<_i2.UnifiedPlantData>>.value(
            <_i2.UnifiedPlantData>[]),
      ) as _i4.Future<List<_i2.UnifiedPlantData>>);

  @override
  _i4.Future<_i2.UnifiedPlantData?> getPlantById(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlantById,
          [plantId],
        ),
        returnValue: _i4.Future<_i2.UnifiedPlantData?>.value(),
      ) as _i4.Future<_i2.UnifiedPlantData?>);

  @override
  _i4.Future<_i2.UnifiedGardenStats> getGardenStats(String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGardenStats,
          [gardenId],
        ),
        returnValue:
            _i4.Future<_i2.UnifiedGardenStats>.value(_FakeUnifiedGardenStats_1(
          this,
          Invocation.method(
            #getGardenStats,
            [gardenId],
          ),
        )),
      ) as _i4.Future<_i2.UnifiedGardenStats>);

  @override
  _i4.Future<List<_i2.UnifiedActivityHistory>> getRecentActivities(
    String? gardenId, {
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentActivities,
          [gardenId],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i2.UnifiedActivityHistory>>.value(
            <_i2.UnifiedActivityHistory>[]),
      ) as _i4.Future<List<_i2.UnifiedActivityHistory>>);

  @override
  void invalidateCache(String? gardenId) => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [gardenId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic>? getIntelligenceCache(String? gardenId) =>
      (super.noSuchMethod(Invocation.method(
        #getIntelligenceCache,
        [gardenId],
      )) as Map<String, dynamic>?);

  @override
  void setIntelligenceCache(
    String? gardenId,
    Map<String, dynamic>? data,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setIntelligenceCache,
          [
            gardenId,
            data,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateGardenIntelligenceCache(String? gardenId) =>
      super.noSuchMethod(
        Invocation.method(
          #invalidateGardenIntelligenceCache,
          [gardenId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAllIntelligenceCaches() => super.noSuchMethod(
        Invocation.method(
          #clearAllIntelligenceCaches,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getIntelligenceCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getIntelligenceCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<Map<String, dynamic>> healthCheck() => (super.noSuchMethod(
        Invocation.method(
          #healthCheck,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
