// Mocks generated by Mockito 5.4.4 from annotations
// in permacalendar/test/integration/biological_control_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permacalendar/features/plant_catalog/domain/entities/plant_entity.dart'
    as _i12;
import 'package:permacalendar/features/plant_intelligence/domain/entities/beneficial_insect.dart'
    as _i6;
import 'package:permacalendar/features/plant_intelligence/domain/entities/bio_control_recommendation.dart'
    as _i10;
import 'package:permacalendar/features/plant_intelligence/domain/entities/pest.dart'
    as _i4;
import 'package:permacalendar/features/plant_intelligence/domain/entities/pest_observation.dart'
    as _i8;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_beneficial_insect_repository.dart'
    as _i5;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_bio_control_recommendation_repository.dart'
    as _i9;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_pest_observation_repository.dart'
    as _i7;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_pest_repository.dart'
    as _i2;
import 'package:permacalendar/features/plant_intelligence/domain/repositories/i_plant_data_source.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IPestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPestRepository extends _i1.Mock implements _i2.IPestRepository {
  MockIPestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Pest?> getPest(String? pestId) => (super.noSuchMethod(
        Invocation.method(
          #getPest,
          [pestId],
        ),
        returnValue: _i3.Future<_i4.Pest?>.value(),
      ) as _i3.Future<_i4.Pest?>);

  @override
  _i3.Future<List<_i4.Pest>> getAllPests() => (super.noSuchMethod(
        Invocation.method(
          #getAllPests,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Pest>>.value(<_i4.Pest>[]),
      ) as _i3.Future<List<_i4.Pest>>);

  @override
  _i3.Future<List<_i4.Pest>> getPestsForPlant(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPestsForPlant,
          [plantId],
        ),
        returnValue: _i3.Future<List<_i4.Pest>>.value(<_i4.Pest>[]),
      ) as _i3.Future<List<_i4.Pest>>);

  @override
  _i3.Future<List<_i4.Pest>> searchPests(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchPests,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.Pest>>.value(<_i4.Pest>[]),
      ) as _i3.Future<List<_i4.Pest>>);

  @override
  _i3.Future<List<_i4.Pest>> getPestsBySeverity(_i4.PestSeverity? severity) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPestsBySeverity,
          [severity],
        ),
        returnValue: _i3.Future<List<_i4.Pest>>.value(<_i4.Pest>[]),
      ) as _i3.Future<List<_i4.Pest>>);
}

/// A class which mocks [IBeneficialInsectRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBeneficialInsectRepository extends _i1.Mock
    implements _i5.IBeneficialInsectRepository {
  MockIBeneficialInsectRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.BeneficialInsect?> getInsect(String? insectId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsect,
          [insectId],
        ),
        returnValue: _i3.Future<_i6.BeneficialInsect?>.value(),
      ) as _i3.Future<_i6.BeneficialInsect?>);

  @override
  _i3.Future<List<_i6.BeneficialInsect>> getAllInsects() => (super.noSuchMethod(
        Invocation.method(
          #getAllInsects,
          [],
        ),
        returnValue: _i3.Future<List<_i6.BeneficialInsect>>.value(
            <_i6.BeneficialInsect>[]),
      ) as _i3.Future<List<_i6.BeneficialInsect>>);

  @override
  _i3.Future<List<_i6.BeneficialInsect>> getPredatorsOf(String? pestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPredatorsOf,
          [pestId],
        ),
        returnValue: _i3.Future<List<_i6.BeneficialInsect>>.value(
            <_i6.BeneficialInsect>[]),
      ) as _i3.Future<List<_i6.BeneficialInsect>>);

  @override
  _i3.Future<List<_i6.BeneficialInsect>> getInsectsAttractedTo(
          String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getInsectsAttractedTo,
          [plantId],
        ),
        returnValue: _i3.Future<List<_i6.BeneficialInsect>>.value(
            <_i6.BeneficialInsect>[]),
      ) as _i3.Future<List<_i6.BeneficialInsect>>);

  @override
  _i3.Future<List<_i6.BeneficialInsect>> searchInsects(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchInsects,
          [query],
        ),
        returnValue: _i3.Future<List<_i6.BeneficialInsect>>.value(
            <_i6.BeneficialInsect>[]),
      ) as _i3.Future<List<_i6.BeneficialInsect>>);
}

/// A class which mocks [IPestObservationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPestObservationRepository extends _i1.Mock
    implements _i7.IPestObservationRepository {
  MockIPestObservationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> savePestObservation(_i8.PestObservation? observation) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePestObservation,
          [observation],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePestObservation(_i8.PestObservation? observation) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePestObservation,
          [observation],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.PestObservation>> getObservationsForGarden(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObservationsForGarden,
          [gardenId],
        ),
        returnValue: _i3.Future<List<_i8.PestObservation>>.value(
            <_i8.PestObservation>[]),
      ) as _i3.Future<List<_i8.PestObservation>>);

  @override
  _i3.Future<List<_i8.PestObservation>> getActiveObservations(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveObservations,
          [gardenId],
        ),
        returnValue: _i3.Future<List<_i8.PestObservation>>.value(
            <_i8.PestObservation>[]),
      ) as _i3.Future<List<_i8.PestObservation>>);

  @override
  _i3.Future<List<_i8.PestObservation>> getObservationsForPlant(
          String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObservationsForPlant,
          [plantId],
        ),
        returnValue: _i3.Future<List<_i8.PestObservation>>.value(
            <_i8.PestObservation>[]),
      ) as _i3.Future<List<_i8.PestObservation>>);

  @override
  _i3.Future<_i8.PestObservation?> getObservation(String? observationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObservation,
          [observationId],
        ),
        returnValue: _i3.Future<_i8.PestObservation?>.value(),
      ) as _i3.Future<_i8.PestObservation?>);

  @override
  _i3.Future<void> resolveObservation(
    String? observationId,
    String? resolutionMethod,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #resolveObservation,
          [
            observationId,
            resolutionMethod,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteObservation(String? observationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteObservation,
          [observationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [IBioControlRecommendationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBioControlRecommendationRepository extends _i1.Mock
    implements _i9.IBioControlRecommendationRepository {
  MockIBioControlRecommendationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveRecommendation(
          _i10.BioControlRecommendation? recommendation) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRecommendation,
          [recommendation],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i10.BioControlRecommendation>> getRecommendationsForGarden(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendationsForGarden,
          [gardenId],
        ),
        returnValue: _i3.Future<List<_i10.BioControlRecommendation>>.value(
            <_i10.BioControlRecommendation>[]),
      ) as _i3.Future<List<_i10.BioControlRecommendation>>);

  @override
  _i3.Future<List<_i10.BioControlRecommendation>>
      getRecommendationsForObservation(String? observationId) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecommendationsForObservation,
              [observationId],
            ),
            returnValue: _i3.Future<List<_i10.BioControlRecommendation>>.value(
                <_i10.BioControlRecommendation>[]),
          ) as _i3.Future<List<_i10.BioControlRecommendation>>);

  @override
  _i3.Future<_i10.BioControlRecommendation?> getRecommendation(
          String? recommendationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendation,
          [recommendationId],
        ),
        returnValue: _i3.Future<_i10.BioControlRecommendation?>.value(),
      ) as _i3.Future<_i10.BioControlRecommendation?>);

  @override
  _i3.Future<void> markRecommendationApplied(
    String? recommendationId,
    String? userFeedback,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markRecommendationApplied,
          [
            recommendationId,
            userFeedback,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i10.BioControlRecommendation>> getAppliedRecommendations(
          String? gardenId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAppliedRecommendations,
          [gardenId],
        ),
        returnValue: _i3.Future<List<_i10.BioControlRecommendation>>.value(
            <_i10.BioControlRecommendation>[]),
      ) as _i3.Future<List<_i10.BioControlRecommendation>>);

  @override
  _i3.Future<void> deleteRecommendation(String? recommendationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRecommendation,
          [recommendationId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [IPlantDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIPlantDataSource extends _i1.Mock implements _i11.IPlantDataSource {
  MockIPlantDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i12.PlantFreezed?> getPlant(String? plantId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlant,
          [plantId],
        ),
        returnValue: _i3.Future<_i12.PlantFreezed?>.value(),
      ) as _i3.Future<_i12.PlantFreezed?>);

  @override
  _i3.Future<List<_i12.PlantFreezed>> getAllPlants() => (super.noSuchMethod(
        Invocation.method(
          #getAllPlants,
          [],
        ),
        returnValue:
            _i3.Future<List<_i12.PlantFreezed>>.value(<_i12.PlantFreezed>[]),
      ) as _i3.Future<List<_i12.PlantFreezed>>);

  @override
  _i3.Future<List<_i12.PlantFreezed>> searchPlants(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue:
            _i3.Future<List<_i12.PlantFreezed>>.value(<_i12.PlantFreezed>[]),
      ) as _i3.Future<List<_i12.PlantFreezed>>);
}
